### ISSUE TITLE
Generate custom token pool via a UI in dev network

### ISSUE THREAD

**Issue by tysloan** [liftedinit/roadmap#21]
Description: This is the front-end work related to #62 . This is for Liftoff Program members and Web2/3 developers who need a custom token on an existing network. The generate custom tokens feature will benefit users who want them for company equity issuances, reward tokens, utility tokens, and more. This functionality should be achievable via a UI (Gwen) for ease-of-use and non-developers. Users should be able to generate an initial custom token pool, like we do at genesis. This story is to send the feature to the dev network. 

Story ROI
Customer Need: A Liftoff Program team has requested a way to generate a custom token on an existing network to replace their in-app currency with a blockchain-based token.

Business Objective: Enabling more development and use cases to occur on the Manifest Network. This can lead to more network usage.

**As a developer, I want to generate custom tokens so that end-users can transact them.**

- [ ] Should be achievable via a UI (Gwen).
- [ ] Should be achievable via library (many-js).
- [ ] Should be available from the network API (many-framework).
- [ ] Should comply with the specification (many-protocol).
- [ ] Should be able to limit the scope to the Manifest dev network.
- [ ] Should be able to generate a new symbol (3-5 letter limit).
- [ ] Should present an error message if the symbol is already taken on the network.
- [ ] Should be able to input the set number of custom tokens that will be generated in the pool.
- [ ] Should be generated to the address that is creating them.
- [ ] Should be able to transact custom tokens after they are generated.
- [ ] Should be able to be demoed in the dev network.
- [ ] Should NOT include minting and burning custom tokens.
- [ ] Should NOT include documentation requirements.
- [ ] Should NOT include sending to QA/staging.

[PRD](https://docs.google.com/document/d/1RhJcAMI_kS1wPsAhAL9STbk1r20cplPUbuwSVee3bRQ/edit?usp=sharing).

[Design](https://www.figma.com/file/u4f5cQDN86LtRQdBGQe10J/Gwen---Network-Control-Panel?node-id=875%3A2983)

![Image](https://user-images.githubusercontent.com/113936517/200379842-d3dffc9b-c79f-4584-9bba-bdcacfae2cbc.png)

----------------
Tasks

- [ ] Define specification.
- [ ] Write implementation.
        a. many-js
        b. many-framework & Gwen
- [ ] Write tests.
- [ ] Propagate to the dev environment.
- [ ] Demo the story to the team (local & dev network) (Feature branch).

Question:
- What if someone tries to spam the network to acquire as many token symbols as possible?

**Comment by tysloan** [comment]
@stanleyjones are there missing front-end Requirements/Tasks for this story that should be added?

**Comment by fmorency** [comment]
@stanleyjones Here's a mock file you can use to test. It _should_ work but I can't actually test it. Let me know!


```
"ledger.info" = """
{
    0: [
        10000_1(h'01df3d94be0460def4f38e5d7d77b7ed87e588f40e95cb192c8c3569f1'),
        10000_1(h'011835a9c812fed5a18dc63743109bf2526632caa871e6b1eca1930c00')
    ],
    1: h'ba7645210390ab0e7f57501608d52b8a7226f7ba7e6809998b0338410a7efe76',
    4: {
        10000_1(h'01df3d94be0460def4f38e5d7d77b7ed87e588f40e95cb192c8c3569f1'): "ABC",
        10000_1(h'011835a9c812fed5a18dc63743109bf2526632caa871e6b1eca1930c00'): "DEF",
    }
}
"""

"tokens.create" = """
{
    0: 10000_1(h'01b258619c7d00f1b1db232363cddc90b97165d54618ac78626119543c'),
    1: {
        0: "Dummy",
        1: "XXX",
        2: 8,
        3: {},
    },
    2: {
        0: 1234567890,
        1: 123456789,
        2: 2000000000,
    },
    3: 10000_1(h'01dd7d0db22b0d8d00cf719c48644a906adb0aeb77abc85f55617b5679'),
}
"""

# TODO: Add memo extended info after memo refactor
# Unicode visual logo is ∑
# PNG visual logo is a 2x2 image. Top left is red, top right is green, bottom left is blue and bottom right is pink
"tokens.info" = """
{
    0: {
        0: 10000_1(h'01b258619c7d00f1b1db232363cddc90b97165d54618ac78626119543c'),
        1: {
            0: "Dummy",
            1: "XXX",
            2: 8,
            3: {},
        },
        2: {
            0: 1234567890,
            1: 123456789,
            2: 2000000000,
        },
        3: 10000_1(h'01dd7d0db22b0d8d00cf719c48644a906adb0aeb77abc85f55617b5679'),
    },
    1: {
        1: [{0: 0, 1: "∑"}, {0: 1, 1: "png", 2: h'89504e470d0a1a0a0000000d4948445200000002000000020802000000fdd49a73000000097048597300002e2300002e230178a53f76000000164944415408d763f8cfc0c0f09f819181e1ff7f0606001cf803fe3d5ff2550000000049454e44ae426082'}],
    }
}
"""
```

**Comment by stanleyjones** [comment]
Front-end work is mostly done, spread across a few PRs:

1) Dumb UI (i.e. no network calls): https://github.com/liftedinit/gwen/pull/17
2) Necessary changes to ManyJS: https://github.com/liftedinit/many-js/pull/81
3) Connect UI to network: https://github.com/liftedinit/gwen/pull/18

**Comment by stanleyjones** [comment]
Reopening as related PRs automatically close.

**Comment by stanleyjones** [comment]
Reopening as related PRs automatically close.

**Comment by stanleyjones** [comment]
Working here: https://dev002_gwen.liftedinit.tech/#/settings/ledger

**Comment by stanleyjones** [comment]
Actually not working.

**Comment by stanleyjones** [comment]
Demoed with the following bugs:

- Surface error to user if not authorized
- Invalidate query cache on successful creation

**Comment by stanleyjones** [comment]
https://github.com/liftedinit/gwen/issues/27
https://github.com/liftedinit/gwen/issues/29
