### ISSUE TITLE
[tracking] Token Authority

### ISSUE THREAD

**Issue by hansl** [liftedinit/roadmap#3]
Allow for a server to mint, burn, detail, transfer, and generally manage tokens. This is not limited to fungible tokens.

## Tasks

- [ ] Delegation. Needed for building a trust relationship between servers.
  - https://github.com/many-protocol/specification/pull/63 (draft)
  - https://github.com/liftedinit/many-rs/pull/205 (draft)
  - Create a proof of concept delegation, including CLI tooling to create certificates.
- [ ] Multisig and counter signed messages. Needed to allow decentralized neighborhoods to collectively sign messages.
- [ ] Inter neighborhood/server messaging for decentralized neighborhood. This allows neighborhoods to communicate between each others.
- [ ] Token specification. Defining what a token is in addition to its identity and human-readable name. e.g. who's its authority, logo, documentation pointers, etc.
  - [x] #11 
- [ ] Token Authority specification. Defining how new tokens are defined by customers, and how they can tell ledger neighborhoods to mint tokens directly into accounts (genesis).
- [ ] Updating Ledger specification (new attribute) to also include 
- [ ] Proof of concept.
- [ ] Implementation.
- [ ] Production.

## Blockers
- [x] https://github.com/liftedinit/roadmap/issues/11

**Comment by hansl** [comment]
# Status

Delegation is specified (https://github.com/many-protocol/specification/pull/63) and clarifies more things than _just_ delegation, so even if it might not be a blocker for inter-neighborhood messaging, it should still be reviewed and merged. Will request a review today or tomorrow.

Proof of concept of Delegation is being worked. As I continue to solve the inter-nh-messaging specification I might put that on hold.

**Comment by hansl** [comment]
Everything is in draft but ready to review soon. @hansl wants to add more tests for the specification. Need to add a `many-framework` PR but this can happen later (`many-rs` is fully backward compatible here).

Target: end of week if I get enough time to finish.

**Comment by hansl** [comment]
This is blocked until we figured out inter neighborhood messaging, but the underlying product need is now tracked in #11 and will be done separately as a manual create/mint/burn tokens.
