### ISSUE TITLE
[tracking] Give the accounts count from Ledger Neighborhood

### ISSUE THREAD

**Issue by hansl** [liftedinit/roadmap#5]
There are 2 tracking sub issues for this:

- Data Attribute (~~many-protocol/specification#56~~)
  This is to serve metrics and measurements from a server. This is not meant to replace Prometheus, only to have an in-protocol way of showing data varz.

- Ledger Data Attribute distributing the number of accounts the Ledger has seen.
  This should also implement a migration step to calculate the count from the database.

## Tasks

- [x] Specification for Data Attribute
  - ~~https://github.com/many-protocol/specification/pull/56~~
- [x] Migration Implementation. To allow for creating database upgrades at certain block height, the height being specified from a configuration file.
  - https://github.com/liftedinit/many-framework/pull/243
- [x] Implementation.
  - https://github.com/liftedinit/many-framework/pull/243
  - Migration Framework.
- [ ] Documentation
  - [x] https://github.com/liftedinit/many-framework/issues/263
- [ ] Production.

**Comment by hansl** [comment]
# Status
Implementing the tracking part to count accounts (see specification).

- Q: Are you making sure this is hidden behind a migration step?
  Yes.

**Comment by hansl** [comment]
Yuri working on resilience tests and fixing the problem before ready to review. 

Target to have https://github.com/liftedinit/many-framework/pull/243 ready for review; tomorrow or Wednesday. Review timeline is at risk for EOW, might be early next week. Targeting next week for merging and creating a release.

**Comment by hansl** [comment]
PR is ready to review. @hansl to do that today.

**Comment by fmorency** [comment]
@fmorency is still working on design + poc.

**Comment by hansl** [comment]
Closing this in preference to https://github.com/liftedinit/roadmap/issues/29
