### ISSUE TITLE
Tendermint 0.35 to 0.34 downgrade in QA

### ISSUE THREAD

**Issue by hansl** [liftedinit/roadmap#6]
Tendermint 0.35 has been officially abandoned, with work moving from 0.34 to 0.37. 0.37 is currently in alpha.

## Tasks

- [x] Figure out the best approach to upgrade, or if the status quo is good enough for us. See liftedinit/many-rs#200.

**Comment by hansl** [comment]
@fmorency encountered a bug last Friday that made him try using TM 0.34. Modifications to the code isn't too heavy. Did not test creating a hybrid network.  Knows how to move to 0.34.

We can move to tendermint-rpc 0.25 and use tendermint 0.34 for NEW neighborhood. More tests need to happen for ledger neighborhood.

**Comment by fmorency** [comment]
Pushed down to after END labs deployment. Timeframe TBD.

**Comment by tysloan** [comment]
Description: Tendermint 0.35 has been abandoned and is no longer supported. We need to first move to Tendermint 0.34 to be to upgrade to 0.37 which is the overall end target. This is necessary to increase our security and stability. This has already been researched as noted above. Production nodes have not been upgraded since August. 

Story ROI
Business Objective: By moving to Tendermint 0.34 we will then be able to upgrade to 0.37 and increase security.

**As an engineer, I want to migrate from Tendermint 0.35 to 0.34 to increase stability and security.** 

- [ ] ~Should clone production network to QA environment.~ Removed during estimation.
- [x] Should test alternative compute instances in AWS for reducing sync time
- [x] Should run migration to downgrade network to Tendermint 0.34 hybrid network in QA environment.
- [x] Should create latest RC to include with Tendermint 0.34.
- [x] Should snapshot data from fully-synced node to all additional 15 nodes.
- [x] Should execute RC15 Upgrade with Tendermint 0.35 running all nodes
- [x] Should re-run downgrade to Tendermint 34 with RC15-tm34 release across all QA hosts
- [x] Should thoroughly test Tendermint 0.34 downgrade on nodes (including stress, migration, and network stability tests).
- [ ] Should fork A vs. B BATS to execute against a list of remote nodes and test all transaction types.  - will be removed to separate issue.
- [x] Should document procedure plan to run prod migration and downgrade from Tendermint 0.35 to 0.34. 

--------------------
Tasks:

**Comment by fmorency** [comment]
@tysloan Let's split the TM upgrade and the RC9 upgrade. Let's move to TM 0.34 first.

**Comment by tysloan** [comment]
@fmorency split up and made RC9 upgrade here in #46 . @fmorency @jgryffindor please feel free to edit for accuracy and additional known requirements.

**Comment by fmorency** [comment]
If possible, we should work on implementing, testing, and documenting ways of migrating nodes without resetting them from 0. E.g., TM snapshots, "poor's man" snapshots, etc.

Migrating a whole network will take forever, i.e., multiple months, without a strategy other than resetting the nodes.

**Comment by fmorency** [comment]
I'm not sure it is realistic to expect the migration of the prod network to TM 0.34 at the end of this sprint.

I believe this sprint should focus on
- Getting a clone of prod running in QA
- Test TM downgrade on nodes. 
  - The number of nodes will depend on the database migration strategy.
- Acquire metrics and test network stability over at least one week
- Stress tests

Q: How hard is it to clone the main network?
Q: Could we do multiple clones?
Q: Should we forward the requests from the main network to one of the clone?

**Comment by jgryffindor** [comment]
I concur about the scope, this ticket should just be testing in QA and planning for prod. The end result won't likely be an entire QA network downgraded to 34, but successful tests of a hybrid network.

**Comment by fmorency** [comment]
RC7 for TM 34 can be found at https://github.com/liftedinit/many-framework/releases/tag/0.1.0-alpha-rc7-tm34

**Comment by fmorency** [comment]
RC14 for TM 34 can be found at https://github.com/liftedinit/many-rs/releases/tag/0.1.0-alpha-rc14-tm34

**Comment by tysloan** [comment]
@jgryffindor @fmorency BATS requirement to separate story.
