### ISSUE TITLE
Snapshot support for Tendermint networks

### ISSUE THREAD

**Issue by hansl** [liftedinit/roadmap#9]
Tendermint supports snapshots in its API to help catch up and save. We should add all the necessary endpoints to `many-abci` and the tendermint attributes to support snapshots in our code.

https://github.com/liftedinit/many-framework/pull/73 was an attempt to add support for it, we need to revise and improve (and test) the PR.

# Tasks

- [ ] Explore what tasks are needed for success here.

**Comment by fmorency** [comment]
Bandwith is limited. Postponed until we have more eng.

**Comment by tysloan** [comment]
Description: Tendermint supports snapshots in its API to help catch nodes up and save. We should add all the necessary endpoints to many-abci and the tendermint attributes to support snapshots in our code. https://github.com/liftedinit/many-framework/pull/73 was an attempt to add support for it, we need to revise and improve (and test) the PR (from Hans' comment above).

Story ROI:
Business objective: By adding snapshop support for Tendermint networks we can save time on infrastructure work and well as decrease the amount of time it takes for nodes to catch up.

**As an engineer, I want snapshot support for Tendermint networks so that time is saved on infrastructure work and node recovery.** 

- [ ] Should implement and test snapshot support functionalities.
- [ ] Should add all the necessary endpoints to many-abci and the Tendermint attributes to support snapshots in our code.
- [ ] Should create documentation for the snapshot process and how to use it.
- [ ] Should be demoed in QA.

-------------
Tasks:
